/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemedicineRouteImport } from './routes/telemedicine'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRecordsRouteImport } from './routes/health-records'
import { Route as AmbulanceRouteImport } from './routes/ambulance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPatientRouteImport } from './routes/dashboard.patient'
import { Route as DashboardDoctorRouteImport } from './routes/dashboard.doctor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const TelemedicineRoute = TelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRecordsRoute = HealthRecordsRouteImport.update({
  id: '/health-records',
  path: '/health-records',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceRoute = AmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/dashboard/patient',
  path: '/dashboard/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: '/dashboard/doctor',
  path: '/dashboard/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/health-records': typeof HealthRecordsRoute
  '/login': typeof LoginRoute
  '/pharmacy': typeof PharmacyRoute
  '/register': typeof RegisterRoute
  '/telemedicine': typeof TelemedicineRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/health-records': typeof HealthRecordsRoute
  '/login': typeof LoginRoute
  '/pharmacy': typeof PharmacyRoute
  '/register': typeof RegisterRoute
  '/telemedicine': typeof TelemedicineRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/health-records': typeof HealthRecordsRoute
  '/login': typeof LoginRoute
  '/pharmacy': typeof PharmacyRoute
  '/register': typeof RegisterRoute
  '/telemedicine': typeof TelemedicineRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambulance'
    | '/health-records'
    | '/login'
    | '/pharmacy'
    | '/register'
    | '/telemedicine'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambulance'
    | '/health-records'
    | '/login'
    | '/pharmacy'
    | '/register'
    | '/telemedicine'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
  id:
    | '__root__'
    | '/'
    | '/ambulance'
    | '/health-records'
    | '/login'
    | '/pharmacy'
    | '/register'
    | '/telemedicine'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbulanceRoute: typeof AmbulanceRoute
  HealthRecordsRoute: typeof HealthRecordsRoute
  LoginRoute: typeof LoginRoute
  PharmacyRoute: typeof PharmacyRoute
  RegisterRoute: typeof RegisterRoute
  TelemedicineRoute: typeof TelemedicineRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDoctorRoute: typeof DashboardDoctorRoute
  DashboardPatientRoute: typeof DashboardPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemedicine': {
      id: '/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof TelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-records': {
      id: '/health-records'
      path: '/health-records'
      fullPath: '/health-records'
      preLoaderRoute: typeof HealthRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance': {
      id: '/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/dashboard/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/dashboard/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbulanceRoute: AmbulanceRoute,
  HealthRecordsRoute: HealthRecordsRoute,
  LoginRoute: LoginRoute,
  PharmacyRoute: PharmacyRoute,
  RegisterRoute: RegisterRoute,
  TelemedicineRoute: TelemedicineRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDoctorRoute: DashboardDoctorRoute,
  DashboardPatientRoute: DashboardPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
